#define MEDIA_KEY_USB_NONE 0x0000
#define MEDIA_KEY_BLE_NONE 0x00000000

static const uint8_t PROGMEM KEYBOARD_MATRIX[6][17] = {
  {KEY_NONE, KEY_ESC, KEY_F1, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_F10, KEY_F11, KEY_F12, KEY_SYSRQ, KEY_SCROLLLOCK, KEY_PAUSE},
  {KEY_NONE, KEY_GRAVE, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0, KEY_MINUS, KEY_EQUAL, KEY_BACKSPACE, KEY_INSERT, KEY_HOME},
  {KEY_NONE, KEY_TAB, KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P, KEY_LEFTBRACE, KEY_RIGHTBRACE, KEY_BACKSLASH, KEY_DELETE, KEY_END},
  {KEY_NONE, KEY_CAPSLOCK, KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_H, KEY_J, KEY_K, KEY_L, KEY_SEMICOLON, KEY_APOSTROPHE, KEY_ENTER, KEY_NONE, KEY_NONE, KEY_PAGEUP},
  {KEY_NONE, KEY_LEFTSHIFT, KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M, KEY_COMMA, KEY_DOT, KEY_SLASH, KEY_RIGHTSHIFT, KEY_UP, KEY_NONE, KEY_NONE, KEY_PAGEDOWN},
  {KEY_NONE, KEY_RIGHTCTRL, KEY_LEFTGUI, KEY_LEFTALT, KEY_NONE, KEY_NONE, KEY_RIGHTALT, KEY_RIGHTGUI, KEY_NONE, KEY_RIGHTCTRL, KEY_LEFT, KEY_DOWN, KEY_RIGHT, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE}
};

static const uint8_t PROGMEM KEYBOARD_MATRIX_FN[6][17] = {
  {KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE},
  {KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE},
  {KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE},
  {KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE},
  {KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE},
  {KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE},
};

static const uint8_t PROGMEM KEYBOARD_MATRIX_FN_SHIFT[6][17] = {
  {KEY_NONE, KEY_NONE, KEY_F13, KEY_F14, KEY_F15, KEY_F16, KEY_F17, KEY_F18, KEY_F19, KEY_F20, KEY_F21, KEY_F22, KEY_F23, KEY_F24, KEY_NONE, KEY_NONE, KEY_NONE},
  {KEY_NONE, KEY_NONE, KEY_KP1, KEY_KP2, KEY_KP3, KEY_KP4, KEY_KP5, KEY_KP6, KEY_KP7, KEY_KP8, KEY_KP9, KEY_KP0, KEY_KPMINUS, KEY_KPPLUS, KEY_NONE, KEY_NONE, KEY_NONE},
  {KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_KPEQUAL, KEY_KPLEFTPAREN, KEY_KPRIGHTPAREN, KEY_KPCOMMA, KEY_KPDOT, KEY_KPASTERISK, KEY_KPSLASH, KEY_NONE, KEY_NONE},
  {KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NUMLOCK, KEY_KPENTER, KEY_NONE, KEY_NONE, KEY_NONE},
  {KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE},
  {KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE},
};

static const uint16_t PROGMEM KEYBOARD_MATRIX_MEDIA_KEYS_USB[6][17] = {
  {MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, CONSUMER_CONTROL_CONFIGURATION, CONSUMER_CONTROL_EMAIL_READER, CONSUMER_CONTROL_CALCULATOR, CONSUMER_CONTROL_LOCAL_BROWSER, CONSUMER_CONTROL_BRIGHTNESS_DECREMENT, CONSUMER_CONTROL_BRIGHTNESS_INCREMENT, CONSUMER_CONTROL_SCAN_PREVIOUS, CONSUMER_CONTROL_PLAY_PAUSE, CONSUMER_CONTROL_SCAN_NEXT, CONSUMER_CONTROL_MUTE, CONSUMER_CONTROL_VOLUME_DECREMENT, CONSUMER_CONTROL_VOLUME_INCREMENT, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE},
  {MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, CONSUMER_CONTROL_POWER, CONSUMER_CONTROL_RESET, CONSUMER_CONTROL_SLEEP, CONSUMER_CONTROL_SEARCH, CONSUMER_CONTROL_HOME, CONSUMER_CONTROL_BACK, CONSUMER_CONTROL_FORWARD, CONSUMER_CONTROL_BR_STOP, CONSUMER_CONTROL_REFRESH, CONSUMER_CONTROL_BOOKMARKS, CONSUMER_CONTROL_REWIND, CONSUMER_CONTROL_FAST_FORWARD, CONSUMER_CONTROL_RECORD, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE},
  {MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE},
  {MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE},
  {MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE},
  {MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE, MEDIA_KEY_USB_NONE}
};

static const uint32_t PROGMEM KEYBOARD_MATRIX_MEDIA_KEYS_BLE[6][17] = {
  {MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, KEY_MEDIA_MYCOMPUTER, KEY_MEDIA_MAIL, KEY_MEDIA_CALCULATOR, KEY_MEDIA_MEDIASELECT, KEY_MEDIA_RANDOMPLAY, KEY_MEDIA_REPEAT, KEY_MEDIA_PREVIOUSTRACK, KEY_MEDIA_PLAYPAUSE, KEY_MEDIA_NEXTTRACK, KEY_MEDIA_MUTE, KEY_MEDIA_VOLUMEDOWN, KEY_MEDIA_VOLUMEUP, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE},
  {MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, KEY_MEDIA_WWWSEARCH, KEY_MEDIA_WWWHOME, KEY_MEDIA_WWWBACK, MEDIA_KEY_BLE_NONE, KEY_MEDIA_WWWSTOP, MEDIA_KEY_BLE_NONE, KEY_MEDIA_WWWFAVORITES, KEY_MEDIA_REWIND, KEY_MEDIA_FASTFORWARD, KEY_MEDIA_RECORD, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE},
  {MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE},
  {MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE},
  {MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE},
  {MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE, MEDIA_KEY_BLE_NONE}
};

//Media keys
/*CONSUMER_CONTROL_POWER
CONSUMER_CONTROL_RESET
CONSUMER_CONTROL_SLEEP

CONSUMER_CONTROL_BRIGHTNESS_DECREMENT
CONSUMER_CONTROL_BRIGHTNESS_INCREMENT

KEY_MEDIA_RANDOMPLAY
KEY_MEDIA_REPEAT

CONSUMER_CONTROL_SCAN_PREVIOUS KEY_MEDIA_PREVIOUSTRACK
CONSUMER_CONTROL_PLAY_PAUSE KEY_MEDIA_PLAYPAUSE
CONSUMER_CONTROL_SCAN_NEXT KEY_MEDIA_NEXTTRACK
CONSUMER_CONTROL_MUTE KEY_MEDIA_MUTE
CONSUMER_CONTROL_VOLUME_DECREMENT KEY_MEDIA_VOLUMEDOWN
CONSUMER_CONTROL_VOLUME_INCREMENT KEY_MEDIA_VOLUMEUP

CONSUMER_CONTROL_REWIND KEY_MEDIA_REWIND
CONSUMER_CONTROL_FAST_FORWARD KEY_MEDIA_FASTFORWARD
CONSUMER_CONTROL_RECORD KEY_MEDIA_RECORD

CONSUMER_CONTROL_CONFIGURATION KEY_MEDIA_MYCOMPUTER
CONSUMER_CONTROL_EMAIL_READER KEY_MEDIA_MAIL
CONSUMER_CONTROL_CALCULATOR KEY_MEDIA_CALCULATOR
CONSUMER_CONTROL_LOCAL_BROWSER KEY_MEDIA_MEDIASELECT

CONSUMER_CONTROL_SEARCH KEY_MEDIA_WWWSEARCH
CONSUMER_CONTROL_HOME KEY_MEDIA_WWWHOME
CONSUMER_CONTROL_BACK KEY_MEDIA_WWWBACK 
CONSUMER_CONTROL_FORWARD
CONSUMER_CONTROL_BR_STOP KEY_MEDIA_WWWSTOP
CONSUMER_CONTROL_REFRESH
CONSUMER_CONTROL_BOOKMARKS KEY_MEDIA_WWWFAVORITES*/